### ISSUE TITLE
Towny + LuckPerms issue

### ISSUE THREAD

**Issue by Blackyvk** [lucko/LuckPerms#1098]
There is a weird issue with towny, that sometimes a user doesnt get their permissions from townyperms, and I have to run /lp sync to make it work, is there a way to fix this permanently?

I changed this **sync-minutes: 3** to the luckperms config to see if it works, havent tested it yet, as the issue is random, I  never had this issue before with PermissionsEx.

the only changed i have made in my lp config.yml are

split storage: enabled: true 
use-server-uuid-cache: true

I'm using LuckPerms 4.1.63 and towny  0.92.0.10 spigot 1.12.2

**Comment by merjilin** [comment]
Just to be sure, please update to the latest build. You're almost 200 builds out of date https://ci.lucko.me/job/LuckPerms/

**Comment by lucko** [comment]
Good chance this has been fixed already, so as merj said, please try updating first :)

**Comment by RubenStryker** [comment]
This error is back in Towny 0.93.1.0, Spigot 1.13.2, LuckyPerm version 4.3.38.

**Comment by RubenStryker** [comment]
Update: With luckyperm version 4.3.47, it's the same

**Comment by Draycia** [comment]
LuckPerms*

**Comment by RubenStryker** [comment]
Thank you very much for this correction that was so necessary

**Comment by Andre601** [comment]
> Thank you very much for this correction that was so necessary

I mean you call it LuckyPerms 🤷‍♂️

**Comment by lucko** [comment]
Open a new issue with all of the information you have please. :)
