### ISSUE TITLE
Space nick problem 

### ISSUE THREAD

**Issue by sewek333** [lucko/LuckPerms#2036]
Space nick problem 
Comand /lp user "xxx xxx" parent add rand
Dont work

**Comment by Andre601** [comment]
This is not an issue as player names (not nicknames) can't have spaces in them.
So you have to use the actual player name or their UUID.

**Comment by sewek333** [comment]
I want to give rang a player "Czesław Miłosz" this nick xbox

**Comment by sewek333** [comment]
Pls help my

**Comment by Andre601** [comment]
That is something that @lucko has to look into

**Comment by lucko** [comment]
> Dont work

Could you elaborate more?

**Comment by sewek333** [comment]
I can't give a player a rank that has spaces in the nick name (Xbox Account)

**Comment by lucko** [comment]
What error messages do you get?

**Comment by lucko** [comment]
Will probably be fixed by making sure `allow-invalid-usernames` is set to true in your config file.

**Comment by Toper9636** [comment]
I still have this problem. A player has a space in his nickname, for example "DAF MERKURIY", and when I try to give him rights, I get the message that the command is not recognized

/luckperms user "DAF MERKURIY" parent set donater

I also want to say that I have set `allow-invalid-usernames=true`, but it didn't help.
![image](https://github.com/LuckPerms/LuckPerms/assets/102699826/34352a66-9c19-4400-9a05-bbfa62f8d9d9)

**Comment by Toper9636** [comment]
Ah, if you use uuid, everything works.
