### ISSUE TITLE
[error] Mysql: Could not send query: Broken pipe (Write failed)

### ISSUE THREAD

**Issue by FrozenBeard** [lucko/LuckPerms#247]
Im getting this error when the servers empty and I join, also it appears when I start the server up, it seems to still save to the database, but what does this warning mean? should I be worried?
```
[02:23:33] [Craft Scheduler Thread - 22/WARN]: [Craft Scheduler Thread - 22] WARN com.zaxxer.hikari.pool.PoolBase - luckperms - Failed to validate connection org.mariadb.jdbc.MariaDbConnection@274d13ff ((conn:27731) Could not read packet: unexpected end of stream, read 0 bytes from 4
Query is : /* LuckPerms ping */ SELECT 1)
[02:23:33] [Craft Scheduler Thread - 22/WARN]: [Craft Scheduler Thread - 22] WARN com.zaxxer.hikari.pool.PoolBase - luckperms - Failed to validate connection org.mariadb.jdbc.MariaDbConnection@79fa3922 ((conn:27732) Could not send query: Broken pipe (Write failed))
[02:23:33] [Craft Scheduler Thread - 22/WARN]: [Craft Scheduler Thread - 22] WARN com.zaxxer.hikari.pool.PoolBase - luckperms - Failed to validate connection org.mariadb.jdbc.MariaDbConnection@3279fd0b ((conn:27733) Could not send query: Broken pipe (Write failed))
[02:23:33] [Craft Scheduler Thread - 22/WARN]: [Craft Scheduler Thread - 22] WARN com.zaxxer.hikari.pool.PoolBase - luckperms - Failed to validate connection org.mariadb.jdbc.MariaDbConnection@24c35589 ((conn:27734) Could not send query: Broken pipe (Write failed))
[02:23:33] [Craft Scheduler Thread - 22/WARN]: [Craft Scheduler Thread - 22] WARN com.zaxxer.hikari.pool.PoolBase - luckperms - Failed to validate connection org.mariadb.jdbc.MariaDbConnection@66eb754e ((conn:27735) Could not send query: Broken pipe (Write failed))
[02:23:33] [Craft Scheduler Thread - 22/WARN]: [Craft Scheduler Thread - 22] WARN com.zaxxer.hikari.pool.PoolBase - luckperms - Failed to validate connection org.mariadb.jdbc.MariaDbConnection@4ef07398 ((conn:27736) Could not send query: Broken pipe (Write failed))
[02:23:33] [Craft Scheduler Thread - 22/WARN]: [Craft Scheduler Thread - 22] WARN com.zaxxer.hikari.pool.PoolBase - luckperms - Failed to validate connection org.mariadb.jdbc.MariaDbConnection@331c5ee8 ((conn:27737) Could not send query: Broken pipe (Write failed))
[02:23:33] [Craft Scheduler Thread - 22/WARN]: [Craft Scheduler Thread - 22] WARN com.zaxxer.hikari.pool.PoolBase - luckperms - Failed to validate connection org.mariadb.jdbc.MariaDbConnection@d4d3a1f ((conn:27738) Could not send query: Broken pipe (Write failed))
[02:23:33] [Craft Scheduler Thread - 22/WARN]: [Craft Scheduler Thread - 22] WARN com.zaxxer.hikari.pool.PoolBase - luckperms - Failed to validate connection org.mariadb.jdbc.MariaDbConnection@30b16ffd ((conn:27739) Could not send query: Broken pipe (Write failed))
[02:23:33] [Craft Scheduler Thread - 22/WARN]: [Craft Scheduler Thread - 22] WARN com.zaxxer.hikari.pool.PoolBase - luckperms - Failed to validate connection org.mariadb.jdbc.MariaDbConnection@7d90b6c0 ((conn:27740) Could not send query: Broken pipe (Write failed))
[02:23:33] [User Authenticator #2/INFO]: UUID of player GodsDead is 93e8b4dc-672b-41c6-bb75-e68960d60184
[02:23:33] [Server thread/INFO]: GodsDead[/123.123.123.123:48851] logged in with entity id 9 at ([Test2]469.0698748355363, 31.0, 822.6709988277371)
[02:23:33] [Server thread/INFO]: > Avast ye! Buccaneer GodsDead » has come aboard!
zzz

**Comment by lucko** [comment]
Issue with your MySQL server. Has nothing to do with LuckPerms.

Check your connection settings, and make sure your server has good access to the server. The broken pipe error would suggest there's a networking issue somewhere.

**Comment by FrozenBeard** [comment]
Connection settings are fine, Once a user has joined it seems to disappear.  MySQL is on the same machine, its connecting to localhost.. What could be wrong? how do I diagnose it?

**Comment by lucko** [comment]
Weird. Are you running a fairly recent MariaDB version?

**Comment by FrozenBeard** [comment]
Yeah, from memory it's something like 10.1 and I have their repo so it updates with apt get update.

**Comment by lucko** [comment]
Do you have any other plugins which are loading the MariaDB libraries?

**Comment by lucko** [comment]
Assuming this is fixed?

**Comment by FrozenBeard** [comment]
Nope its not fixed! I just read your reply when I was busy at work and didn't have time to respond, then forgot.

No other plugins using MariaDB libraries that im aware of, they all seem to use MySQL libraries .

**Comment by lucko** [comment]
Can you try using the standard MySQL driver instead?

**Comment by FrozenBeard** [comment]
yeah sure, ill give it a bash.
