### ISSUE TITLE
Error in console [Sponge]

### ISSUE THREAD

**Issue by SnowBlitzz** [lucko/LuckPerms#274]
https://pastebin.com/tUrjS3ry

**Comment by lucko** [comment]
Which version of LP are you using?

**Comment by SnowBlitzz** [comment]
3.0.65. I figured I'll need to update but wanted to report it just in case. 

Is there anything important I need to know before updating to 3.1.x versions?

**Comment by lucko** [comment]
Nope.

**Comment by lucko** [comment]
Fixed?

**Comment by SnowBlitzz** [comment]
Unfortunately it still exists in the latest version of LP for sponge 3.1.45

This is my config settings https://pastebin.com/qTK5Mc4d

**Comment by lucko** [comment]
Can you pastebin the error it's giving you on the newest version?

**Comment by SnowBlitzz** [comment]
Didn't seem like there was a difference but here: https://pastebin.com/mWqpL190

**Comment by lucko** [comment]
Yeah ok, same error.

In short, this is because LuckPerms was unable to retrieve a "ScriptEngine". Java 8 comes prepackaged with a JavaScript runtime called Nashorn. LuckPerms makes use of this for parsing expressions in default assignments, and also in the filters for the verbose command.

Basically, it's not present on your system. I don't really know what the fix is, but I guess a first step would be to completely uninstall and then reinstall Java. If that doesn't help, then my next guess would be another mod/plugin messing with the class loader, preventing it from finding the nashorn jar.
