### ISSUE TITLE
Inheritance issue when converting storage databases.

### ISSUE THREAD

**Issue by WizzleBear** [lucko/LuckPerms#839]
I went from H2 to YAML and it said it generated several errors, most relating to "all does not exist" when trying to make a group have the inheritance of all the groups.

**Comment by lucko** [comment]
Which version of LuckPerms are you using? (`/lp` will tell you :p)

**Comment by WizzleBear** [comment]
v4.1.25

**Comment by lucko** [comment]
Can you try updating to the latest dev build. I'm fairly sure this issue was fixed in 47739344816560d482f88cc00ff3dce4b68d295f

https://ci.lucko.me/job/LuckPerms/

**Comment by WizzleBear** [comment]
Can you do an inheritance all command?

**Comment by WizzleBear** [comment]
Hmmm... It still doesn't work. Let me give you the exact error.
https://pastebin.com/LrLACLBb

**Comment by lucko** [comment]
You can probably ignore all of those errors. The bulk of your data was applied correctly - looks like those entries were invalid.
